---
- name: Upgrade all packages to the latest version for Ubuntu
  apt:
    name: "*"
    state: latest
  when: (ansible_facts['distribution'] == "Ubuntu")
  tags: prerequisite

- name: Download docker installation script
  get_url:
    url: https://releases.rancher.com/install-docker/19.03.8.sh
    dest: /root/19.03.8.sh
    mode: '0755'
  tags: prerequisite

- name: Launch docker installation script
  command: /root/19.03.8.sh