---
- name: Upgrade all packages to the latest version for Ubuntu
  apt:
    name: "*"
    state: latest
  when: (ansible_facts['distribution'] == "Ubuntu")
  tags: prerequisite

- name: Download docker installation script
  get_url:
    url: https://releases.rancher.com/install-docker/{{ docker_version }}.sh
    dest: /root/{{ docker_version }}.sh
    mode: '0755'
  tags: prerequisite

- name: Check if /run/docker exist - Exit if not
  stat:
    path: /run/docker
  register: foundedDir
  tags: prerequisite

- name: Thinking to do
  debug:
    msg: "Directory exist. Skipping installation"
  when: foundedDir.stat.isdir is defined
  tags: prerequisite

- name: Launch docker installation script
  command: /root/{{ docker_version }}.sh
  when: foundedDir.stat.isdir is not defined
  become: yes
  tags: prerequisite
